import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito_Sans } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/context/query-provider";
import { ThemeProvider } from "@/context/theme-provider";
import { FontProvider } from "@/context/font-provider";
import { DirectionProvider } from "@/context/direction-provider";
import ToastProvider from "@/context/toast-providers";
import { TooltipProvider } from "@/components/ui/tooltip";

const nunitoSans = Nunito_Sans({ variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "DutaShop",
    template: "DutaShop - %s", // <-- template judul dinamis
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunitoSans.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <ThemeProvider>
            <FontProvider>
              <DirectionProvider>
                <ToastProvider>
                  <TooltipProvider>
                    {children}
                  </TooltipProvider>
                </ToastProvider>
              </DirectionProvider>
            </FontProvider>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
